# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.14'

inputs:
- name: gpupgrade_src

outputs:
- name: build_artifacts

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cd gpupgrade_src
    export GOFLAGS="-mod=readonly" # do not update dependencies during build

    make
    GOBIN=$(realpath ../build_artifacts) make install
