# Copyright (c) 2017-2021 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

# Use a Centos/RHEL image to build the rpms
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
    tag: "latest"

inputs:
- name: gpupgrade_src

outputs:
- name: built_oss
- name: built_enterprise

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cd gpupgrade_src
    export GOFLAGS="-mod=readonly" # do not update dependencies during build

    make oss-rpm
    ci/scripts/verify-rpm.bash gpupgrade-*.rpm "Open Source"
    mv gpupgrade-*.rpm ../built_oss

    make enterprise-rpm
    ci/scripts/verify-rpm.bash gpupgrade-*.rpm "Enterprise"
    mv gpupgrade-*.rpm ../built_enterprise

