PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: "7-gcc6.2-llvm3.7"

inputs:
- name: gpupgrade_src
  path: go/src/github.com/greenplum-db/gpupgrade
- name: gpdb_src
- name: bin_gpdb
- name: bats

run:
  path: go/src/github.com/greenplum-db/gpupgrade/ci/scripts/install-tests.bash
