# Copyright (c) 2017-2021 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test-golang
    tag: "latest"

inputs:
- name: gpupgrade_src
- name: gpdb_src_source
- name: rpm_gpdb_source
- name: rpm_gpdb_target
- name: bats

run:
  path: gpupgrade_src/ci/scripts/install-tests.bash
