# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golangci/golangci-lint
    tag: 'v1.23'

inputs:
- name: gpupgrade_src

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    make lint
