# Copyright (c) 2017-2021 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  # Use docker-image instead of registry-image due to the following error.
  # See: https://github.com/concourse/registry-image-resource/issues/283
  #  --- FAIL: TestLocal (0.00s)
  #    disk_test.go:269: Local.Filesystems() returned error &fs.PathError{Op:"open", Path:"/etc/mtab", Err:0x2}
  #    disk_test.go:272: Local.Filesystems() returned no entries
  #  FAIL
  #  FAIL	github.com/greenplum-db/gpupgrade/utils/disk	0.030s
  type: docker-image
  source:
    repository: golang
    tag: '1.16'

inputs:
- name: gpupgrade_src
- name: bats

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    apt update
    apt install -y rsync

    ./bats/install.sh /usr/local

    # Run unit tests as a non-root user since some tests rely on specifying file
    # permissions which are overridden by root.
    adduser  --disabled-password --gecos "" --ingroup tty --shell /bin/bash gpadmin
    chmod -R a+w gpupgrade_src

    su gpadmin -c '
      set -ex

      export TERM=linux
      export GOFLAGS="-mod=readonly" # do not update dependencies during build

      cd gpupgrade_src
      make
      make check --keep-going
    '
