# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.14'

inputs:
- name: gpupgrade_src
  path: ../../../go/src/github.com/greenplum-db/gpupgrade
- name: bats

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export TERM=linux
    ./bats/install.sh /usr/local

    cd $GOPATH/src/github.com/greenplum-db/gpupgrade
    export GOFLAGS="-mod=readonly" # do not update dependencies during build

    make
    make check --keep-going
