set_failed_anchor: &set_failed
  do:
  - task: on_failure_set_failed
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotaldata/ccp
          tag: "7"
      inputs:
        - name: ccp_src
        - name: terraform
      run:
        path: 'ccp_src/google/ccp_failed_test.sh'
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        GOOGLE_SERVICE_ACCOUNT: {{google-service-account}}
        AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
        AWS_DEFAULT_REGION: {{tf-machine-region}}
        BUCKET_PATH: clusters-google/
        BUCKET_NAME: {{tf-bucket-name}}

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
    vars:
      project_id: {{google-project-id}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      bucket: gpdb5-pipeline-dynamic-terraform
      bucket_path: clusters-google/

- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: bin_gpdb4_centos6
  type: s3
  source:
    access_key_id: {{gpdb4-bucket-access-key-id}}
    bucket: {{gpdb4-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{gpdb4-bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: bin_gpdb5_centos6
  type: s3
  source:
    access_key_id: {{ccp-gpdb-binary-bucket-access-key-id}}
    bucket: {{ccp-gpdb-binary-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{ccp-gpdb-binary-bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos6/bin_gpdb.tar.gz

- name: bin_gpdb6_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: gpupgrade_src
  type: git
  source:
    branch: {{gpupgrade-git-branch}}
    uri: https://github.com/greenplum-db/gpupgrade
    ignore_paths:
    - README*

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

jobs:

- name: create_multinode_cluster
  ensure:
    <<: *set_failed
  max_in_flight: 1
  plan:
  - aggregate:
    - get: ccp_src
    - get: gpdb_src
    - get: gpupgrade_src
    - get: centos-gpdb-dev-6
    - get: bin_gpdb4_centos6
    - get: bin_gpdb5_centos6
      trigger: true
    - get: bin_gpdb6_centos6
      trigger: true
  - put: terraform
    params:
      action: create
      delete_on_failure: true
      generate_random_name: true
      terraform_source: ccp_src/google/
      vars:
        instance_type: n1-standard-2
        PLATFORM: centos6
        ccp_reap_minutes: 240
        number_of_nodes: 2

  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-region}}
      BUCKET_PATH: clusters-google/
      BUCKET_NAME: {{tf-bucket-name}}
      CLOUD_PROVIDER: google
      PLATFORM: centos6
    input_mapping:
      gpdb_binary: {{initial-cluster-gpdb-binary}}

  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml

  - task: setup_clusters
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: toolsmiths/ccp
          tag: "7"
      inputs:
      - name: terraform
      - name: ccp_src
      - name: cluster_env_files
      - name: gpupgrade_src
      - name: {{upgraded-cluster-gpdb-binary}}
      run:
        path: gpupgrade_src/pipelines/setup_clusters.sh
        args:
          - 2
          - {{upgraded-cluster-gpdb-binary}}
      params:
        DEBUG_UPGRADE: {{enable-debug-output}}
